/*
 * generated by Xtext 2.20.0
 */
package org.xtext.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathinterpreterStandaloneSetup extends MathinterpreterStandaloneSetupGenerated {

	def static void doSetup() {
		new MathinterpreterStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
