/*
 * generated by Xtext 2.20.0
 */
package org.xtext.mdsd.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MathinterpreterUiModule extends AbstractMathinterpreterUiModule {
	def Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return ExpressionsHoverProvider
	}
}
